# The directory where the .arb files (your language literals) are located.
arb-dir: lib/literals/l10n

# The template .arb file that all other language files will be based on.
# This file should contain all the keys that will be used in the app.
template-arb-file: app_en.arb

# The name of the generated Dart file that will contain your localizations.
# The Flutter tool will create this file for you automatically.
output-localization-file: app_localizations.dart

# Optional: You can specify a class name for the generated localizations class.
# If you don't, it will default to AppLocalizations.
# output-class: AppLocalizations 
Explanation:

# arb-dir: lib/literals/l10n: This tells the localization tool to look inside the lib/literals/l10n directory for your language files.
# template-arb-file: app_en.arb: This sets the English file (app_en.arb) as the master template. All other language files 
# must contain the same keys as this one.
# output-localization-file: app_localizations.dart: This specifies the name of the Dart file that will be 
# automatically generated by Flutter. You will use the class inside this file to access your strings in the UI.